version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/bikebot
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: 
