services:
  bot:
    build: .
    env_file: .env
    environment:
      - NODE_ENV=staging
      - USE_WEBHOOK=false
      - MONGODB_URI=mongodb://mongodb:27017/bikebot
    depends_on:
      - mongodb
    restart: no

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: no

volumes:
  mongodb_data: 
